Dz1
RyaNGosling2/2024-2-VK-EDU-Frontend-D-Astakhov pull request #1
Opened 2024-09-25 21:15 UTC by RyaNGosling2

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1marbur1

2024-09-26 13:42 UTC, 1MarBur1 requested changes

2024-09-26 13:42 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {return false;}
Что будет если передам NaN, Infinity?

2024-09-26 13:42 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +  const cutBts = bytes.toFixed(2).replace(/\.00$/, '');
Нам здесь не нужно использовать регулярки, можем просто преобразовать string в Number, нули отбросятся сами)

2024-09-26 13:42 UTC, 1MarBur1 commented on convertBytesToHuman.js
> +  while (bytes >= 1024 && i < 5)
давай заменим i < 5 на i < unit.length 

сразу поддержим небольшую масштабируемость)

2024-09-26 13:42 UTC, 1MarBur1 commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false)
пройдись по проекту и расставь точки с запятой

2024-09-26 13:42 UTC, 1MarBur1 commented on correctSentence.js
> +  if(text.charAt(text.length-1) !== ".") { text += ".";}
заменим .charAt(text.length-1) на .at(-1)

и давай если у нас фигурные скобки в одну строку не будем ставить ; 

Будет выглядеть лучше) Вообще задание со звездочкой - можешь настроить eslint)

2024-09-26 13:42 UTC, 1MarBur1 commented on nonUniqueElements.js
> +        let ndx = data.indexOf(data[i]);
Лишняя строчка, здесь всегда ndx = i

2024-09-26 13:42 UTC, 1MarBur1 commented on nonUniqueElements.js
> +        data.splice(ndx, 1);}
Давай мы не будем изменять вводные данные, а создадим новый массив result. И еще не стоит изменять массив, по которому бежим, даже если не изменяем указатель

2024-09-27 10:49 UTC, RyaNGosling2 commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {return false;}
Теперь для этих случаев проверки появилась.

2024-09-30 16:05 UTC, 1MarBur1 approved these changes
@martinkomitsky @HaseProgram @kgrechin approved

2024-10-01 18:45 UTC, merged

2024-10-01 18:45 UTC, martinkomitsky commented
12!