Dz2
RyaNGosling2/2024-2-VK-EDU-Frontend-D-Astakhov pull request #2
Opened 2024-10-06 18:06 UTC by RyaNGosling2

# Домашнее задание № 2

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1MarBur1  проверить его.

2024-10-07 21:17 UTC, 1MarBur1 requested changes, later dismissed
<img width="1440" alt="Снимок экрана 2024-10-08 в 00 16 03" src="https://github.com/user-attachments/assets/a49372dc-0a26-4078-b442-5d776abfacd9">

картинки не подгружаются, css тоже как-будто немного не работает)

отправить сообщение тоже не могу, посмотри, что с деплоем?

2024-10-07 21:17 UTC, 1MarBur1 commented on simple-chat/build/bundle.js
добавь билд в гитигнор

2024-10-23 16:58 UTC, martinkomitsky commented
@1MarBur1 комменты?

2024-10-24 20:55 UTC, 1MarBur1 commented
не могу отсмотреть ревью, пока висят node_modules, банально интерфейс глючит)

в гитигноре:
**/node_modules
и туда же можешь добавить 
**/build

2024-10-27 18:09 UTC, martinkomitsky commented
> не могу отсмотреть ревью, пока висят node_modules, банально интерфейс глючит)
> 
> в гитигноре: **/node_modules и туда же можешь добавить **/build

<img width="167" alt="image" src="https://github.com/user-attachments/assets/ee7ce62b-a279-4353-ba0c-9bb5f448a4d6">
реально, выглядит страшно( @RyaNGosling2 Поправь, пожалуйста, как можно скорее и мы поедем дальше!

2024-11-19 14:39 UTC, martinkomitsky approved these changes

2024-11-19 14:39 UTC, martinkomitsky commented
7

2024-11-19 14:40 UTC, merged